#!/usr/bin/env python3
"""
force_16x9.py — Force all images in a folder to exactly 1920×1080 (YouTube 16:9)

Strategy: CROP-TO-FILL — scale so the image covers the full 1920×1080 frame
and center-crop to fit. No black bars. Content fills the entire frame.

Why no black bars: generated images are often square or portrait.
Instead of padding, we scale up until both dimensions are at least 1920×1080,
then center-crop to exactly 1920×1080. Center-crop preserves the most
important content (subjects are almost always centered by the AI generator).

Usage:
    python scripts/force_16x9.py <visuals_folder>
    python scripts/force_16x9.py <visuals_folder> --keep-originals

Output:
    Overwrites each .png in-place with 1920x1080 version.
    Saves original as <name>_orig.png if --keep-originals flag is used.
"""
import subprocess
import sys
from pathlib import Path


def force_16x9(image_path: Path, keep_original: bool = False) -> bool:
    """Convert a single image to 1920x1080 via crop-to-fill (no black bars)."""
    if keep_original:
        orig = image_path.with_name(image_path.stem + "_orig" + image_path.suffix)
        image_path.rename(orig)
        src = str(orig)
    else:
        src = str(image_path)

    dst = str(image_path.with_name(image_path.stem + "_16x9.png"))

    # Crop-to-fill strategy:
    #   scale=1920:1080:force_original_aspect_ratio=increase
    #     → scale up until BOTH dimensions are >= target (no black bars)
    #   crop=1920:1080
    #     → center-crop to exact 1920×1080
    #
    # This is the opposite of the "decrease+pad" approach which adds black bars.
    # Subjects generated by AI are almost always centered, so center-crop is safe.
    cmd = [
        "ffmpeg", "-y",
        "-i", src,
        "-vf", (
            "scale=1920:1080:force_original_aspect_ratio=increase,"
            "crop=1920:1080"
        ),
        "-q:v", "1",   # max quality (JPEG-scale; PNG is lossless anyway)
        dst
    ]

    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"  [ERROR] ffmpeg failed on {image_path.name}: {result.stderr[-300:]}")
        return False

    # Replace original with the 16:9 version
    out = Path(dst)
    out.rename(image_path)
    print(f"  [OK] {image_path.name} → 1920x1080 (crop-to-fill)")
    return True


def main():
    if len(sys.argv) < 2:
        print("Usage: python force_16x9.py <visuals_folder> [--keep-originals]")
        sys.exit(1)

    folder = Path(sys.argv[1])
    keep = "--keep-originals" in sys.argv

    if not folder.exists():
        print(f"[ERROR] Folder not found: {folder}")
        sys.exit(1)

    images = sorted(
        list(folder.glob("*.png")) +
        list(folder.glob("*.jpg")) +
        list(folder.glob("*.jpeg"))
    )

    if not images:
        print(f"[WARN] No images found in: {folder}")
        sys.exit(0)

    print(f"[force_16x9] Processing {len(images)} image(s) in {folder}")
    print(f"[force_16x9] Mode: crop-to-fill (no black bars) → 1920x1080")
    converted = 0
    for img in images:
        if "_orig" in img.stem or "_16x9" in img.stem:
            continue  # skip backup files
        if force_16x9(img, keep_original=keep):
            converted += 1

    print(f"\n[force_16x9] Done. {converted}/{len(images)} converted to 1920x1080.")


if __name__ == "__main__":
    main()
